#!/bin/csh
# TODO use bash
echo '================================================================='
foreach file (SPEX_*.?cov spex_*.?cov)
        echo $file
        grep "#####" $file
        echo '================================================================='
        end
