#!/bin/sh

./cholupdate lp_sctap1 > Outputs/CholUpdate/lp_sctap1_chol.out
./cholupdate lp_bandm > Outputs/CholUpdate/lp_bandm_chol.out
./cholupdate lp_agg3 > Outputs/CholUpdate/lp_agg3_chol.out
./cholupdate lp_greenbeb > Outputs/CholUpdate/lp_greenbeb_chol.out
./cholupdate lp_scagr7 > Outputs/CholUpdate/lp_scagr7_chol.out
./cholupdate lp_ken_11 > Outputs/CholUpdate/lp_ken_11_chol.out
./cholupdate lp_maros > Outputs/CholUpdate/lp_maros_chol.out
./cholupdate lp_scagr25 > Outputs/CholUpdate/lp_scagr25_chol.out
./cholupdate lp_blend > Outputs/CholUpdate/lp_blend_chol.out
./cholupdate lp_capri > Outputs/CholUpdate/lp_capri_chol.out
