#!/bin/sh

./cholupdate lp_scfxm2 > Outputs/CholUpdate/lp_scfxm2_chol.out
./cholupdate lp_scsd6 > Outputs/CholUpdate/lp_scsd6_chol.out
./cholupdate lp_ship12l > Outputs/CholUpdate/lp_ship12l_chol.out
./cholupdate lp_israel > Outputs/CholUpdate/lp_israel_chol.out
./cholupdate lp_sc105 > Outputs/CholUpdate/lp_sc105_chol.out
./cholupdate lp_scfxm1 > Outputs/CholUpdate/lp_scfxm1_chol.out
./cholupdate lp_sc50b > Outputs/CholUpdate/lp_sc50b_chol.out
./cholupdate lp_80bau3b > Outputs/CholUpdate/lp_80bau3b_chol.out
./cholupdate lp_pilot_we > Outputs/CholUpdate/lp_pilot_we_chol.out
./cholupdate lp_pilotnov > Outputs/CholUpdate/lp_pilotnov_chol.out
