#!/bin/sh

./cholupdate lp_scrs8 > Outputs/CholUpdate/lp_scrs8_chol.out
./cholupdate lp_ken_13 > Outputs/CholUpdate/lp_ken_13_chol.out
./cholupdate lp_qap8 > Outputs/CholUpdate/lp_qap8_chol.out
./cholupdate lp_afiro > Outputs/CholUpdate/lp_afiro_chol.out
./cholupdate lp_grow15 > Outputs/CholUpdate/lp_grow15_chol.out
./cholupdate lp_scorpion > Outputs/CholUpdate/lp_scorpion_chol.out
./cholupdate lp_agg > Outputs/CholUpdate/lp_agg_chol.out
./cholupdate lp_cre_c > Outputs/CholUpdate/lp_cre_c_chol.out
./cholupdate lp_pds_10 > Outputs/CholUpdate/lp_pds_10_chol.out
./cholupdate lp_ganges > Outputs/CholUpdate/lp_ganges_chol.out
