#!/bin/sh

./cholupdate lp_qap15 > Outputs/CholUpdate/lp_qap15_chol.out
./cholupdate lp_sierra > Outputs/CholUpdate/lp_sierra_chol.out
./cholupdate lp_scsd8 > Outputs/CholUpdate/lp_scsd8_chol.out
./cholupdate lp_pds_02 > Outputs/CholUpdate/lp_pds_02_chol.out
./cholupdate lp_share1b > Outputs/CholUpdate/lp_share1b_chol.out
./cholupdate lp_qap12 > Outputs/CholUpdate/lp_qap12_chol.out
./cholupdate lp_ship04s > Outputs/CholUpdate/lp_ship04s_chol.out
./cholupdate lp_stocfor3 > Outputs/CholUpdate/lp_stocfor3_chol.out
./cholupdate lp_ken_18 > Outputs/CholUpdate/lp_ken_18_chol.out
./cholupdate lp_cre_a > Outputs/CholUpdate/lp_cre_a_chol.out
