#!/bin/sh

./ptest lp_maros > Outputs/lp_maros_chol.out
./ptest lp_maros_r7 > Outputs/lp_maros_r7_chol.out
./ptest lp_modszk1 > Outputs/lp_modszk1_chol.out
./ptest lp_osa_07 > Outputs/lp_osa_07_chol.out
./ptest lp_osa_14 > Outputs/lp_osa_14_chol.out
./ptest lp_osa_30 > Outputs/lp_osa_30_chol.out
./ptest lp_osa_60 > Outputs/lp_osa_60_chol.out
./ptest lp_pds_02 > Outputs/lp_pds_02_chol.out
./ptest lp_pds_06 > Outputs/lp_pds_06_chol.out
./ptest lp_pds_10 > Outputs/lp_pds_10_chol.out
./ptest lp_pds_20 > Outputs/lp_pds_20_chol.out
./ptest lp_perold > Outputs/lp_perold_chol.out
./ptest lp_pilot > Outputs/lp_pilot_chol.out # >99hrs
./ptest lp_pilot4 > Outputs/lp_pilot4_chol.out
./ptest lp_pilot87 > Outputs/lp_pilot87_chol.out
./ptest lp_pilot_ja > Outputs/lp_pilot_ja_chol.out
