#!/bin/sh

./ptest lp_fit2d > Outputs/lp_fit2d_chol.out
./ptest lp_fit2p > Outputs/lp_fit2p_chol.out
./ptest lp_ganges > Outputs/lp_ganges_chol.out
./ptest lp_gfrd_pnc > Outputs/lp_gfrd_pnc_chol.out
./ptest lp_greenbea > Outputs/lp_greenbea_chol.out
./ptest lp_greenbeb > Outputs/lp_greenbeb_chol.out
./ptest lp_grow15 > Outputs/lp_grow15_chol.out
./ptest lp_grow22 > Outputs/lp_grow22_chol.out
./ptest lp_grow7 > Outputs/lp_grow7_chol.out
./ptest lp_israel > Outputs/lp_israel_chol.out
./ptest lp_kb2 > Outputs/lp_kb2_chol.out
./ptest lp_ken_07 > Outputs/lp_ken_07_chol.out
./ptest lp_ken_11 > Outputs/lp_ken_11_chol.out
./ptest lp_ken_13 > Outputs/lp_ken_13_chol.out
./ptest lp_ken_18 > Outputs/lp_ken_18_chol.out
./ptest lp_lotfi > Outputs/lp_lotfi_chol.out
#./ptest lpi_qual > Outputs/lpi_qual_chol.out
#./ptest lpi_reactor > Outputs/lpi_reactor_chol.out
#./ptest lpi_refinery > Outputs/lpi_refinery_chol.out
#./ptest lpi_vol1 > Outputs/lpi_vol1_chol.out
#./ptest lpi_woodinfe > Outputs/lpi_woodinfe_chol.out
