#!/bin/sh

./ptest lp_pilot_we > Outputs/lp_pilot_we_chol.out
./ptest lp_pilotnov > Outputs/lp_pilotnov_chol.out
./ptest lp_qap12 > Outputs/lp_qap12_chol.out
./ptest lp_qap15 > Outputs/lp_qap15_chol.out
./ptest lp_qap8 > Outputs/lp_qap8_chol.out
./ptest lp_recipe > Outputs/lp_recipe_chol.out
./ptest lp_sc105 > Outputs/lp_sc105_chol.out
./ptest lp_sc205 > Outputs/lp_sc205_chol.out
./ptest lp_sc50a > Outputs/lp_sc50a_chol.out
./ptest lp_sc50b > Outputs/lp_sc50b_chol.out
./ptest lp_scagr25 > Outputs/lp_scagr25_chol.out
./ptest lp_scagr7 > Outputs/lp_scagr7_chol.out
./ptest lp_scfxm1 > Outputs/lp_scfxm1_chol.out
./ptest lp_scfxm2 > Outputs/lp_scfxm2_chol.out
./ptest lp_scfxm3 > Outputs/lp_scfxm3_chol.out
./ptest lp_scorpion > Outputs/lp_scorpion_chol.out
