#!/bin/sh

./ptest lp_scrs8 > Outputs/lp_scrs8_chol.out
./ptest lp_scsd1 > Outputs/lp_scsd1_chol.out
./ptest lp_scsd6 > Outputs/lp_scsd6_chol.out
./ptest lp_scsd8 > Outputs/lp_scsd8_chol.out
./ptest lp_sctap1 > Outputs/lp_sctap1_chol.out
./ptest lp_sctap2 > Outputs/lp_sctap2_chol.out
./ptest lp_sctap3 > Outputs/lp_sctap3_chol.out
./ptest lp_share1b > Outputs/lp_share1b_chol.out
./ptest lp_share2b > Outputs/lp_share2b_chol.out
./ptest lp_shell > Outputs/lp_shell_chol.out
./ptest lp_ship04l > Outputs/lp_ship04l_chol.out
./ptest lp_ship04s > Outputs/lp_ship04s_chol.out
./ptest lp_ship08l > Outputs/lp_ship08l_chol.out
./ptest lp_ship08s > Outputs/lp_ship08s_chol.out
./ptest lp_ship12l > Outputs/lp_ship12l_chol.out
./ptest lp_ship12s > Outputs/lp_ship12s_chol.out
#./ptest lpi_klein2 > Outputs/lpi_klein2_chol.out
#./ptest lpi_klein3 > Outputs/lpi_klein3_chol.out
#./ptest lpi_mondou2 > Outputs/lpi_mondou2_chol.out

