#!/bin/sh

#./ptest lp_cre_b > Outputs/lp_cre_b_chol.out
./ptest lp_cre_c > Outputs/lp_cre_c_chol.out
./ptest lp_cre_d > Outputs/lp_cre_d_chol.out
./ptest lp_cycle > Outputs/lp_cycle_chol.out
./ptest lp_czprob > Outputs/lp_czprob_chol.out
./ptest lp_d2q06c > Outputs/lp_d2q06c_chol.out
./ptest lp_d6cube > Outputs/lp_d6cube_chol.out
./ptest lp_degen2 > Outputs/lp_degen2_chol.out
./ptest lp_degen3 > Outputs/lp_degen3_chol.out
./ptest lp_e226 > Outputs/lp_e226_chol.out
./ptest lp_etamacro > Outputs/lp_etamacro_chol.out
./ptest lp_fffff800 > Outputs/lp_fffff800_chol.out
./ptest lp_finnis > Outputs/lp_finnis_chol.out
./ptest lp_fit1d > Outputs/lp_fit1d_chol.out
./ptest lp_fit1p > Outputs/lp_fit1p_chol.out
#./ptest lp_dfl001 > Outputs/lp_dfl001_chol.out
